// <auto-generated />
using System;
using ISGKkdTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISGKkdTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718143728_RemoveToplamKisi")]
    partial class RemoveToplamKisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISGKkdTakip.Models.Mekan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mekanlar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Rapor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EkipmanKullanan")
                        .HasColumnType("integer");

                    b.Property<int>("MekanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UygunsuzlukId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MekanId");

                    b.HasIndex("UygunsuzlukId");

                    b.ToTable("Raporlar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Uygunsuzluk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Uygunsuzluklar");
                });

            modelBuilder.Entity("RaporUygunsuzluk", b =>
                {
                    b.Property<int>("RaporId")
                        .HasColumnType("integer");

                    b.Property<int>("UygunsuzlukId")
                        .HasColumnType("integer");

                    b.Property<int?>("UygunsuzlukId1")
                        .HasColumnType("integer");

                    b.HasKey("RaporId", "UygunsuzlukId");

                    b.HasIndex("UygunsuzlukId");

                    b.HasIndex("UygunsuzlukId1");

                    b.ToTable("RaporUygunsuzluklar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Rapor", b =>
                {
                    b.HasOne("ISGKkdTakip.Models.Mekan", "Mekan")
                        .WithMany("Raporlar")
                        .HasForeignKey("MekanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISGKkdTakip.Models.Uygunsuzluk", "Uygunsuzluk")
                        .WithMany("Raporlar")
                        .HasForeignKey("UygunsuzlukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mekan");

                    b.Navigation("Uygunsuzluk");
                });

            modelBuilder.Entity("RaporUygunsuzluk", b =>
                {
                    b.HasOne("ISGKkdTakip.Models.Rapor", "Rapor")
                        .WithMany("RaporUygunsuzluklar")
                        .HasForeignKey("RaporId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISGKkdTakip.Models.Uygunsuzluk", "Uygunsuzluk")
                        .WithMany()
                        .HasForeignKey("UygunsuzlukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISGKkdTakip.Models.Uygunsuzluk", null)
                        .WithMany("RaporUygunsuzluklar")
                        .HasForeignKey("UygunsuzlukId1");

                    b.Navigation("Rapor");

                    b.Navigation("Uygunsuzluk");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Mekan", b =>
                {
                    b.Navigation("Raporlar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Rapor", b =>
                {
                    b.Navigation("RaporUygunsuzluklar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Uygunsuzluk", b =>
                {
                    b.Navigation("RaporUygunsuzluklar");

                    b.Navigation("Raporlar");
                });
#pragma warning restore 612, 618
        }
    }
}
