// <auto-generated />
using System;
using ISGKkdTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISGKkdTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250708073820_IlkOlusturma")]
    partial class IlkOlusturma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ISGKkdTakip.Models.Mekan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mekanlar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Rapor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EkipmanKullanan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MekanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToplamKisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UygunsuzlukId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MekanId");

                    b.HasIndex("UygunsuzlukId");

                    b.ToTable("Raporlar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Uygunsuzluk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uygunsuzluklar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Rapor", b =>
                {
                    b.HasOne("ISGKkdTakip.Models.Mekan", "Mekan")
                        .WithMany("Raporlar")
                        .HasForeignKey("MekanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISGKkdTakip.Models.Uygunsuzluk", "Uygunsuzluk")
                        .WithMany("Raporlar")
                        .HasForeignKey("UygunsuzlukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mekan");

                    b.Navigation("Uygunsuzluk");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Mekan", b =>
                {
                    b.Navigation("Raporlar");
                });

            modelBuilder.Entity("ISGKkdTakip.Models.Uygunsuzluk", b =>
                {
                    b.Navigation("Raporlar");
                });
#pragma warning restore 612, 618
        }
    }
}
